#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generates locale string files for all launch languages (master spec §2).

Usage: python3 tools/i18n/generate.py
Reads tools/i18n/strings_<locale>.py dictionaries and writes
<module>/src/main/res/values-<qualifier>/strings.xml for each module.
Brand names (app_name, onboarding_app_name) are intentionally not
translated; they fall back to the default locale.
"""
import importlib.util
import pathlib
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[2]
TOOLS = ROOT / "tools" / "i18n"

MODULES = {
    "app": "android/app/src/main/res",
    "data": "android/data/src/main/res",
    "contacts": "android/feature/contacts/src/main/res",
    "calls": "android/feature/calls/src/main/res",
    "settings": "android/feature/settings/src/main/res",
    "chats": "android/feature/chats/src/main/res",
    "onboarding": "android/feature/onboarding/src/main/res",
}

# Never translated: brand identity stays identical in every locale.
NEVER_TRANSLATE = {"app_name", "onboarding_app_name"}

LOCALES = ["hi", "ur", "ar", "bn", "es", "fr", "pt-rBR", "in", "tr", "ru"]


def master_strings():
    """(module -> [names in file order]) from the default values/strings.xml."""
    result = {}
    for module, rel in MODULES.items():
        path = ROOT / rel / "values" / "strings.xml"
        tree = ET.parse(path)
        names = [el.get("name") for el in tree.getroot() if el.tag == "string"]
        result[module] = [n for n in names if n not in NEVER_TRANSLATE]
    return result


def escape(text):
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("'", "\u2019")  # typographic apostrophe needs no XML escaping
    )


def load_locale(locale):
    module_key = locale.replace("-r", "_r").lower()
    path = TOOLS / f"strings_{module_key}.py"
    if not path.exists():
        path = TOOLS / f"strings_{locale.lower()}.py"
    spec = importlib.util.spec_from_file_location(f"strings_{locale}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return dict(mod.STRINGS)


def main():
    master = master_strings()
    failures = 0
    for locale in LOCALES:
        data = load_locale(locale)
        for module, names in master.items():
            entries = []
            missing = []
            for name in names:
                value = data.get((module, name))
                if value is None:
                    missing.append(name)
                    continue
                entries.append(f'    <string name="{name}">{escape(value)}</string>')
            if missing:
                failures += len(missing)
                print(f"MISSING {locale}/{module}: {missing}")
                continue
            out_dir = ROOT / MODULES[module] / f"values-{locale}"
            out_dir.mkdir(parents=True, exist_ok=True)
            body = "\n".join(entries)
            content = (
                '<?xml version="1.0" encoding="utf-8"?>\n'
                "<!-- Generated by tools/i18n/generate.py — edit the dictionaries, not this file. -->\n"
                f"<resources>\n{body}\n</resources>\n"
            )
            (out_dir / "strings.xml").write_text(content, encoding="utf-8")
        print(f"{locale}: done")
    if failures:
        print(f"{failures} missing translations")
        sys.exit(1)
    print("All locales generated.")


if __name__ == "__main__":
    main()
